const bcrypt = require('bcrypt');

const User = require('../models/user');
const routes = require('express').Router();

routes.get('/:id', (req, res) => {
  res.status(200).json({
    _id: req.params.id,
    name: "Ging Gonzalez",
    email: "ginggonzalez3@gmail.com",
    address: {
        street: "",
        city: "",
        state: "",
        zip_code: ""
    }
  });
});

routes.post('/create', (req, res) => {
  // Delete the _id property from req.body since _id will be generated by
  // mongoDB as the data is inserted
  delete req.body._id;

  // hash the password
  const saltRounds = 10;

  bcrypt.hash(req.body.password, saltRounds)
    .then(hash => {
      req.body.password = hash;

      // Add user to the database
      User.create(req.body, (err, res) => {
        if (err) {
          console.log("Could not insert User");
        } else {
          console.log("Successfuly inserted User");
        }
      });
    });

  res.status(200).json({
    status: "200"
  });
});

routes.post('/login', (req, res) => {
  User.findOne({email: req.body.email})
  .exec((err, user) => {
    if (!err) {
      if (user) {
        bcrypt.compare(req.body.password, user.password)
        .then(res => {
          console.log("This is the answer: " + res);
        });

        res.status(200).json({
          status: "200"
        });
      }
      else {
        res.status(400).json({
          status: "400",
          error: "Bad Request"
        });
      }
    }
    else {
      res.status(500).json({
        status: "500",
        error: "Internal Server Error"
      });
    }
  });
})

module.exports = routes;
